---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DongjianPeng.
--- DateTime: 2022/6/13/0013 23:09
---
-- 注释，--  2个-
print("hello world")

print("------------------分隔线----------------")
-- 基础数据类型
print(type("hello world")) -->output:string
print(type(print))         -->output:function
print(type(true))          -->output:boolean
print(type(360.0))         -->output:number
print(type(nil))           -->output:nil

print("------------------分隔线----------------")
-- nil 空
local num
print(num)        -->output:nil

num = 100
print(num)        -->output:100

print("------------------分隔线----------------")
-- boolean （布尔）
local a = true
local b = 0  -- 切记 lua中只有false和nil是 假，其余为真，和C语言的非0和空字符串为真不一样
local c = nil

if a then
    print("a")  -- 输出了
else
    print("not a")
end

if b then
    print("b") -- 输出了
else
    print("not b")
end

if c then
    print("c")
else
    print("not c") -- 输出了
end

print("------------------分隔线----------------")
-- number（数字）
local order = 3.99
local score = 101.13

print(math.floor(order)) -- 3  地板数
print(math.ceil(score))  --102  天花板数

print(9223372036854775807LL - 1) -- 9223372036854775806LL

print("------------------分隔线----------------")
-- string（字符串）  字符串比较是O(1) 因为有全局哈希表存储，相同字符串内容只会有一个，字符串不可变
local str1 = 'hello world'
local str2 = "hello world"
local str3 = [["add \n na
me",'hello']]  -- \n这种不会被转义
local str4 = [[ [[[[ 嘎嘎i客户尽快 gkdjh 】】[[s]g[[d]g][sd  ]]  -- 只会处理[[ ]] 中间的，不过中间不能有]]

print(str1)
print(str2)
print(str3)
print(str4)

print("------------------分隔线----------------")
-- table（表）  key-value键值对
local corp = {
    web = "www.google.com",   --索引为字符串，key = "web",
    --            value = "www.google.com"
    telephone = "12345678",   --索引为字符串
    staff = {"Jack", "Scott", "Gary"}, --索引为字符串，值也是一个表
    100876,              --相当于 [1] = 100876，此时索引为数字
    --      key = 1, value = 100876
    100191,              --相当于 [2] = 100191，此时索引为数字
    [10] = 360,          --直接把数字索引给出
    ["10"] = 362,          --直接把数字索引给出
    ["city"] = "Beijing" --索引为字符串
}

print(corp.web)               -->output:www.google.com
print(corp["telephone"])      -->output:12345678
print(corp[2])                -->output:100191
print(corp["city"])           -->output:"Beijing"
print(corp.city)               -->output:"Beijing"
print(corp.staff[1])          -->output:Jack
print(corp["staff"][1])          -->output:Jack
print(corp.staff[0])     -->output:nil  （列表下标从1开始？）
print(corp[10])               -->output:360
print(corp["10"])               -->output:nil（如果上面没有"10"）   362

print("------------------分隔线----------------")
-- function函数，在lua中 函数是一种数据类型，可以赋值给另一个变量，可以通过参数传递

local function foo()
    print("in the function")
    -- do xx
    local x = 10
    local y = 20
    return (x + y)
end

local fa = foo()
print(fa) -- 30

local fa2 = foo
print(fa2) -- function: 0x001db398
print(fa2()) -- 30

print(foo)

function foo()

end
print(foo)

foo = function()

end
print(foo)
-- 打印了3个不同的函数地址
