---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DongjianPeng.
--- DateTime: 2022/6/26/0026 17:14
--- 运算符
---
print("------------------分隔线----------------")
-- 算术运算符
print(1 + 2) -- 3
print(0.1 + 0.2) -- 0.3 （Javascript，你脸红不？）
print(10 - 4) -- 6
print(1 - 0.9) -- 0.1 （Javascript，你脸红不？）
print(2 * 8) -- 16
print(2 * 1.5) -- 3
print(10 / -3) -- -3.3333333333333
print(10 / 5) -- 2
print(2 ^ 3) -- 8  指数运算 ，2的3次幂
print(10 % 3) -- 1  取模运算

print("------------------分隔线----------------")
-- 关系运算符
print(1 < 2) -- true
print(1 <= 2) -- true
print(2 > 1)  -- true
print(2 >= 1)  -- true
print(2 == 2)  -- true
print(1 ~= 2) -- true  不等于用的是~=
local a, b = true, false
print(a, b) --true	false
print(a == b) -- false
print(a ~= b) -- true
-- print(a>b) -- 报错：attempt to compare two boolean values

-- 注意，==判断时，table，函数等，是引用比较，只有引用同一个对象是才相等：
local a = { x = 1, y = 0 }
local b = { x = 1, y = 0 }
print(a, b) -- table: 0x001d8118	table: 0x001d8178
if a == b then
    print("a == b")
else
    print("a ~= b") -- a ~= b
end

print("------------------分隔线----------------")
-- 逻辑运算符
local c = nil


print("------------------分隔线----------------")
-- 字符串拼接
