---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DongjianPeng.
--- DateTime: 2022/6/26/0026 18:19
--- 模块
---
print("------------------分隔线----------------")

---- 这个.符号好像是文件夹分隔符 所以导入类似04.function模块是会报错找不到这个模块的
local my_module = require("module.my")

my_module.greeting()

local sum = my_module.sum(1,2,3)
print(sum)

