---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DongjianPeng.
--- DateTime: 2022/6/26/0026 18:21
--- 时间日期函数
---
print("------------------分隔线----------------")
---- 在 OpenResty 的世界里，不推荐使用这里的标准时间函数，因为这些函数通常会引发不止一个昂贵的系统调用，
--- 同时无法为 LuaJIT JIT 编译，对性能造成较大影响。推荐使用 ngx_lua 模块提供的带缓存的时间接口，
---如 ngx.today, ngx.time, ngx.utctime, ngx.localtime, ngx.now, ngx.http_time，以及 ngx.cookie_time 等。
local t1 = os.time()
print(t1)
--字段名称	取值范围
--year	四位数字
--month	1--12
--day	1--31
--hour	0--23
--min	0--59
--sec	0--61
--isdst	boolean（true表示夏令时）
local table2 = { year = 2022, month = 6, day = 30, hour = 8, min = 1, sec = 47 }
local t2 = os.time(table2)
print(t2) -- 1656547307
-- 对比时间差异
print(os.difftime(t1, t2)) -- xxxx 输出的是 t1 - t2 的值，结果可以是负数

print("------------------分隔线----------------")
---- os.date ([format [, time]])
-- format是格式化字符串，time是日期和时间的数字表示，默认当前时间
local tab1 = os.date("*t")  --返回一个描述当前日期和时间的表
print(tab1)
local ans1 = "{"
for k, v in pairs(tab1) do
    --把tab1转换成一个字符串
    ans1 = string.format("%s %s = %s,", ans1, k, tostring(v))
end
ans1 = ans1 .. "}"
print("tab1 = ", ans1)

local tab2 = os.date("*t", 360)  --返回一个描述日期和时间数为360秒的表
local ans2 = "{"

for k, v in pairs(tab2) do
    --把tab2转换成一个字符串
    ans2 = string.format("%s %s = %s,", ans2, k, tostring(v))
end

ans2 = ans2 .. "}"
print("tab2 = ", ans2)

