---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DongjianPeng.
--- DateTime: 2022/6/26/0026 18:21
--- 文件操作
--- 文件 I/O 操作，在 OpenResty 的上下文中对事件循环是会产生阻塞效应
print("------------------分隔线----------------")

local fileName = "09.math.lua"

file = io.input(fileName)  -- 打开文件

repeat
    line = io.read()            -- 逐行读取内容，文件结束时返回nil
    if nil == line then
        break
    end
    print(line)
until (false)

io.close(file)                  -- 关闭文件


file = io.open(fileName, "a+")   -- 使用 io.open() 函数，以添加模式打开文件
io.output(file)                     -- 使用 io.output() 函数，设置默认输出文件
io.write("-- xxxx\n")           -- 使用 io.write() 函数，把内容写到文件
io.close(file)