---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DongjianPeng.
--- DateTime: 2022/6/28/0028 14:36
---
--- 导出模块的说明：
--- 创建一个table，把需要导出的函数放进去，最后返回这个table
--- 切记不能在require函数内上下文切换
local _M = {}

local function get_name()
    return "Lucy"
end

function _M.greeting()
    print("hello " .. get_name())
end

function sum(...)
    local args = { ... }
    local s = 0;
    for i, v in ipairs(args) do
        s = s + v
    end
    return s
end

_M.sum = sum

return _M